---
title: "Algorithm"
author: "Rick SCHNEIDER"
date: "November 26, 2018"
output: html_document
---

```{r}
library(dplyr)
library(tidyr)
library(stringr)
```

```{r}
#import:
data <- read.csv("data/complete_data.csv")
sample_submission <- read.csv("data/sample_submission.csv")

glimpse(data)
glimpse(sample_submission)
```




First we need to do a train/test split.As we deal with a time series problem, we need to repsect the chronological order of events. As a result we cannot do a k-fold evaluation. We are going to implement a 80/20% train/test split:

```{r}

data <- data %>% arrange(visit_date)
View(data)
split_index <- round(nrow(data)*0.8)



#train:
TRAIN <- data[1:split_index,]
#test:
TEST <- data[split_index+1:nrow(data),]

```









Merge with inner_join submission file and data:
```{r}

  
sample_submission <- sample_submission %>% 
                        separate(id, into = c("id","predict_date"), sep=20)  

sample_submission <- sample_submission %>% 
                        separate(predict_date, into = c("error","predict_date"), sep=1) 

sample_submission <- sample_submission %>% 
                        select(-error)

#join sample_submission with data:

sub_join <- inner_join(sample_submission,data,by="id")

glimpse(sub_join)
```





