---
title: "Algorithm"
author: "Rick SCHNEIDER"
date: "November 26, 2018"
output: html_document
---

```{r}
library(dplyr)
library(tidyr)
```

Load all the data in
```{r}
air_reserve <- read.csv("data/air_reserve.csv")                   #check
air_store_info <- read.csv("data/air_store_info.csv")             #check
air_visit_data <- read.csv("data/air_visit_data.csv")             
data_info <- read.csv("data/date_info.csv")                       #check
hpg_reserve <- read.csv("data/hpg_reserve.csv")                   #check
hpg_store_info <- read.csv("data/hpg_store_info.csv")             #check
store_id_relation <- read.csv("data/store_id_relation.csv")       #check
sample_submission <- read.csv("data/sample_submission.csv")
```

```{r}
glimpse(air_reserve)
glimpse(hpg_reserve)
glimpse(store_id_relation)
glimpse(sample_submission)
```

First, we are going to add the hpg_reserve (with changed hpg ids to air ids) to the air_reserve, and call the data set global:
```{r}

#rename to id:
air_reserve <- air_reserve %>% rename(id = air_store_id)
hpg_reserve <- hpg_reserve %>% rename(id = hpg_store_id)


#paste them together:
reserve <- rbind(air_reserve, hpg_reserve)

```

Now, we need to add air_store_info and hpg_store_info.

```{r}
glimpse(air_store_info)
glimpse(hpg_store_info)
```

```{r}
#rename to id:
air_store_info <- air_store_info %>% 
                    rename(id = air_store_id,
                           genre_name = air_genre_name,
                           area_name = air_area_name)
hpg_store_info <- hpg_store_info %>% 
                    rename(id = hpg_store_id,
                           genre_name = hpg_genre_name,
                           area_name = hpg_area_name)

#paste them together:
info <- rbind(air_store_info, hpg_store_info)

```


Now we need to merge reserve and info on id:

```{r}
final <- full_join(reserve,info,by="id")
View(final)
```

Data info:

```{r}
glimpse(final)
glimpse(data_info)
```
 
Join it on the calender date:
```{r}
data_info <- data_info %>% 
                    rename(visit_date= calendar_date)


final <-final %>% 
                separate(visit_datetime, into = c('visit_date', 'visit_time'), sep = 10) %>% 
                separate(reserve_datetime, into = c('reserve_date', 'reserve_time'), sep = 10)
#join
final <- full_join(final,data_info,by="visit_date")
#rename
final <- final %>% 
            rename(day_of_the_week_visit = day_of_week,
                   holiday_flg_visit = holiday_flg)

#for reserve:
data_info <- data_info %>% 
                    rename(reserve_date= visit_date)
final <- full_join(final,data_info,by="reserve_date")
#rename
final <- final %>% 
            rename(day_of_the_week_reserve= day_of_week,
                   holiday_flg_reserve = holiday_flg)

#View(final)
```


```{r}
glimpse(air_visit_data)

air_visit_data <- air_visit_data %>% 
                    rename(id = air_store_id)
glimpse(final)

final2 <- full_join(final,air_visit_data,by=c("id","visit_date"))
glimpse(final2)

```


```{r}
store_id_relation <- store_id_relation  %>% 
                    rename(id = hpg_store_id)
final3 <- full_join(final2, store_id_relation, by= "id")
ind <- !is.na(final3[,"air_store_id"])
final3[ind,"id"] <- as.character(final3[ind,"air_store_id"])

final3 <- final3[,-16]
glimpse(final3)

final3

write.csv(final3, file="data/complete_data.csv", row.names = FALSE) #run only once and check it's in your data folder
final_data <- read.csv("data/complete_data.csv")
final_data
```


final3 is the complete data set!
